### ISSUE TITLE
Inexplicable hanging when opening a certain vue file?

### ISSUE THREAD

**Issue by tylerhsu** [8uff3r/vue-ts-mode#2]
Okay, I've spent hours trying to figure this out and I'm at my wits' end.  I would be surprised if this turns out to be a real bug and not something specific to my setup. If you simply tell me whether you're able to reproduce, I would be grateful.

When I attempt to open the following file with vue-ts-mode turned on, emacs hangs indefinitely and pegs the CPU at 100%:.

```html
<template>
  <div v-if="agreementType1">
            <base-form-row>
              <base-input ref="cashPrice" name="cash_price" />
              <template v-if="!agreementType.recurring_billing">
                <base-input name="sales_tax_rate" />
                <base-input name="sales_tax_amount" />
              </template>
            </base-form-row>
            <base-form-row>
              <base-input name="down_payment" />
              <base-input name="financed_amount" />
              <base-input name="total_balance_due" />
            </base-form-row>
            <base-form-row>
              <base-input name="billing_cycle" />
              <base-input name="number_of_payments" />
            </base-form-row>
            <base-form-row>
              <base-input name="finance_rate_percent" />
              <base-input name="finance_charge" />
              <base-input name="apr" :show-errors="true">
                <template slot="errors" slot-scope="{ field, validation, isActive }">
                  <p v-if="validat"></p>
                </template>
              </base-input>
            </base-form-row>
  </div>
</template>
```

The strange indenting is intentional.

Any one of the following changes gets rid of the hanging:

1. Editing vue-ts-mode.el as follows:
```diff
diff --git a/vue-ts-mode.el b/vue-ts-mode.el
index 69faeb8..0cd495d 100644
--- a/vue-ts-mode.el
+++ b/vue-ts-mode.el
@@ -154,9 +154,9 @@
 
      (interpolation (raw_text) @capture)
 
-     (element (_ (directive_attribute
-                  (quoted_attribute_value
-                   (attribute_value) @capture)))))
+     (directive_attribute
+      (quoted_attribute_value
+       (attribute_value) @capture)))
 
    :embed 'css
    :host 'vue
```

2. Or, editing the file in question as follows:
```diff
24c24
<                   <p v-if="validate"></p>
---
>                   <p v-if="validat"></p>
```
Yes, that's removing the "e".

3. Or, making just about any other change to the file in question, including reducing the indentation of the over-indented middle section by one space.

The tree-sitter cli successfully parses the file in question.

Here's how I've installed vue-ts-mode:
```lisp
(use-package vue-ts-mode
  :mode "\\.vue\\'"
  :load-path ("site-lisp/vue-ts-mode"))
```

emacs 29.2
tree-sitter 0.20.8
https://github.com/8uff3r/vue-ts-mode @ 157476c
https://github.com/ikatyang/tree-sitter-vue @ 91fe275
https://github.com/tree-sitter/tree-sitter-typescript @ d847898
https://github.com/tree-sitter/tree-sitter-css @ 98c7b3d
https://github.com/tree-sitter/tree-sitter-html @ 949b780

**Comment by 8uff3r** [comment]
Hi thanks for the issue!

I've also encountered such issues, unfortunately I think it's a problem with Emacs implementation of tree-sitter, which causes really weird issues.

> 1. Editing vue-ts-mode.el as follows:

If this has improved your experience and you haven't found other problems caused by this change, You could make a pull request with the change.

**Comment by tylerhsu** [comment]
Thank you for taking a look, and thanks for your work by the way.

I'd be happy to open a PR with that change, except it's a direct reversion of this commit you made: https://github.com/8uff3r/vue-ts-mode/commit/acea54d6e2ff33ce817b83987b734e824204b488

Any recollection of why you made the change in the first place?

**Comment by 8uff3r** [comment]
I think there was a bug in treesit that didn't select the directives correctly, unfortunately I can't test it right now, but if after making the change you think the highlighting still works correctly, I don't think there would be a problem with it.
