### ISSUE TITLE
Bad highlighting when using 'libtree-sitter-tsx.so'

### ISSUE THREAD

**Issue by ghost** [8uff3r/vue-ts-mode#5]
Following the README I have a correct result.

`init.el`
```
(load-theme 'wombat)

(setq treesit-language-source-alist
      '((vue "https://github.com/ikatyang/tree-sitter-vue")
        (css "https://github.com/tree-sitter/tree-sitter-css")
        (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")))

(mapc #'treesit-install-language-grammar '(vue css typescript))

(add-to-list 'load-path (concat user-emacs-directory "vue-ts-mode"))
(require 'vue-ts-mode)
```

![with-typescript-only](https://github.com/8uff3r/vue-ts-mode/assets/122544856/00a2dcc3-8a34-4b3a-9f9d-c33f4548b549)

The problem is having `libtree-sitter-tsx.so` in the tree-sitter folder, that causes the highlighting to break. The first 4 lines are not colored.

```
        (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
```

![with-typescript-and-tsx](https://github.com/8uff3r/vue-ts-mode/assets/122544856/66ab264c-74d4-475e-a30e-7a3120190409)

---

GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0) of 2023-09-11, modified by Debian

**Comment by ghost** [comment]
With version 30.0.50 syntax highlighting works correctly.

**Comment by 8uff3r** [comment]
I have changed the typescript parser from tsx back to typescript, so if you encounter any other issues, make sure to have that installed too. I'll update the Readme accordingly.

I had your problem too, it's because of a bug in emacs 29, which has been solved in version 30. I think your other issue was also related to this.
